### ISSUE TITLE
Feature: add dl option to ignore 'File exists' (& same size) cases

### ISSUE THREAD

**Issue by mchubby** [qgustavor/megajs-cli#12]
When downloading a shared directory incrementally over a local copy, one might want to not be flooded with error messages about existing files (assuming if they are the same size, they have not been modified)

Basically, I would like to turn off this report:
https://github.com/qgustavor/megajs-cli/blob/2cec6e6/lib/util.js#L132

**Comment by qgustavor** [comment]
You can send a pull request, otherwise it will take some time (I still need to fix #11, but I'm a bit busy).

**Comment by qgustavor** [comment]
I just checked megatools and it have almost the same behavior. How about a `--skip-downloaded` flag?

By now it would only disable this report, but when file MAC checking is implemented (by fixing [this issue](https://github.com/qgustavor/mega/issues/29)) it could be used to skip this checking. I implemented this feature [as an experiment here](https://cdn.rawgit.com/qgustavor/40b77fa5997d9b1acb5f15d74bbce0b2/raw/) (I know it's a MAC, but I put checksum because it seemed easier to understand).

**Comment by mchubby** [comment]
Yes, I think it makes sense. I don't mind waiting for the other feature to complete either.

**Comment by qgustavor** [comment]
I already fixed the other issue locally, I just need to commit and release a new version, but I will fix this one first. I saw that now megatools defaults to continuing downloads and I think adding a new flag will make the CLI a bit messy (there are already a lot of unimplemented flags). How about this?

- Remove `--continue`, make resuming downloads default.
- Add `--disable-resume` like megatools.
- When syncing folders that message will only be displayed if `--disable-resume` is enabled.

Well, it's not an error if a file already exists. A simpler option would be removing this message entirely. If someone misses that message for some reason, then we can add a `--verbose` flag to restore it.
